### ISSUE TITLE
Criar arquivo .env

### ISSUE THREAD

**Issue by FlightofIcarus** [adailtonasp/adahack-2024-backend#26]
Criar arquivo .env com informações das variáveis de ambiente com informações sensíveis e configuráveis. 

Exemplo: Porta.

**Comment by adailtonasp** [comment]
O arquivo foi criado apenas com as variáveis necessárias para início de desenvolvimento do banco de dados. As variáveis precisarão ser definidas posteriormente de acordo com configuração de acesso ao banco de dados
