### ISSUE TITLE
Criar readme

### ISSUE THREAD

**Issue by adailtonasp** [adailtonasp/adahack-2024-backend#3]
Documentação detalhada do projeto contento:
- Descrição do Problema
- Objetivo do Projeto
- Arquitetura, pattern e ferramentas utilizadas
- Descrição das funcionalidades
- Requisitos funcionais e não funcionais do projeto
- Guia de execução do projeto
- Listagem de membros da squad

**Comment by FlightofIcarus** [comment]
O arquivo readme.md precisa de revisão em alguns pontos, por questão de erros na digitação. Além disto, verifico que tem a informação de que as informações de análise são apresentados ao RH em forma de gráfico. Vamos criar uma interface gráfica para mostrar isso, ou enquanto API, vamos retornar apenas os números para que o front possa a partir de tais informações, montar e exibir um gráfico?

Outro ponto que vejo carente de melhoria, é a parte de requisitos funcionais e não funcionais. Critérios de aceite e requisitos funcionais e não funcionais são questões que até podem ser semelhantes, mas são relativamente diferentes. Nos requisitos funcionais não temos, por exemplo, nenhuma das funcionalidades listadas. Temos um tópico que descreve as funcionalidades, mas em requisitos funcionais, elas não são citadas. 

Para facilitar o entendimento, deixo um link para verificação: [Requisitos funcionais e não funcionais](https://blog.casadodesenvolvedor.com.br/requisitos-funcionais-e-nao-funcionais/)

**Comment by Sownatta** [comment]
Erros de ortografia foram corrigidos. Sessão de requisitos foi reformulada.
