### ISSUE TITLE
Criar validações genéricas para propriedades do tipo String 

### ISSUE THREAD

**Issue by adailtonasp** [adailtonasp/adahack-2024-backend#37]
Os campos de entrada do tipo String devem ser validados verificando o tipo adequado(_typeof_) e seu tamanho mínimo.

**Comment by FlightofIcarus** [comment]
A validação de strings genéricas deve verificar:

- Se é do tipo string
- Se não é uma string vazia
- Se não é uma string composta apenas de espaços em brancos
- Se tem um valor mínimo de 2 caracteres

**Comment by FlightofIcarus** [comment]
Funções básicas de validação de strings criadas, verificando como requisitado, se o input fornecido é do tipo string, se for uma string, se não é vazia, se não é composta apenas de espaços em branco e se tem um valor mínimo de dois caracteres.

Foram criadas funções separadas para validar cada parte, que podem ser reusadas para futuras validações específicas e uma função que verifica todas as validações.
