### ISSUE TITLE
Criar arquivo para inicialização da aplicação (App.js)

### ISSUE THREAD

**Issue by SilvioLucasDev** [adailtonasp/adahack-2024-backend#5]
Criar arquivo de "entrypoint" App.js na raiz do projeto. Este é o arquivo que será chamado ao inicializar a API.

**Comment by adailtonasp** [comment]
Colocar descrição

**Comment by FlightofIcarus** [comment]
O Arquivo app.js na raiz do projeto já foi criado, chamando a exportação abstrata do servidor da API, de forma a garantir mais uma camada de abstração, uma vez que ele apenas chama a inicialização do servidor, não contendo nenhuma informação de configuração.
